
development:
  SENDGRID_USERNAME:
  SENDGRID_PASSWORD:
  TUMBLR_CONSUMER_KEY: 
  TUMBLR_CONSUMER_SECRET: 

production:
  SENDGRID_USERNAME:
  SENDGRID_PASSWORD:
  TUMBLR_CONSUMER_KEY: 
  TUMBLR_CONSUMER_SECRET: 
